### ISSUE TITLE
`fgrosse/phpasn1` is abandoned

### ISSUE THREAD

**Issue by francislavoie** [paragonie/easy-ecc#6]
I'm using `paragonie/easy-ecc` through `paragonie/paseto`, and we're now seeing this warning in Composer:

```
Package fgrosse/phpasn1 is abandoned, you should avoid using it. No replacement was suggested.
```

This is a requirement of `mdanter/ecc`; see https://github.com/phpecc/phpecc/issues/285, a decision hasn't been made yet, but it seems like both `phpecc` and `phpasn1` have fallen out of maintenance.

I know both are pretty stable as-is even if unmaintained, but I think it would be healthy to have maintained forks ready for future PHP version compatibility.

We Paragon be willing to maintain forks of these? I realize that's asking for you to effectively take on more work, but there isn't an org I would trust more :sweat_smile:

**Comment by paragonie-security** [comment]
We'll consider it. I'll update this topic when we have a chance to discuss it further.

**Comment by francislavoie** [comment]
Sounds like https://github.com/paragonie/easy-ecc/releases/tag/v1.0.2 is resolves this?

I'm seeing these are dropped from my project's dependencies after updating:

```
  - Removing phpseclib/phpseclib (2.0.46)
  - Removing mdanter/ecc (v1.0.0)
  - Removing fgrosse/phpasn1 (v2.5.0)
```
