### ISSUE TITLE
Migrationg from Mdanter/ecc - missing curve secg 256r1 ?

### ISSUE THREAD

**Issue by mkrasselt1** [paragonie/easy-ecc#9]
Dear Maintainers -
finaly i am migrationg from mdanter/ecc to this library/repo and my code required SecG Curve 256r1 which i cannot find in this repo.
```
$adapter = EccFactory::getAdapter();
$generator = EccFactory::getSecgCurves()->generator256r1();
```
is there a equivalent in your repo or is this curve just missing - and (how) can i add it ?

Greetings and Thanks for your help.
Michael

**Comment by paragonie-security** [comment]
This is [the same curve as NIST P-256](https://github.com/paragonie/phpecc/blob/6bc975de934f250f8d784207de6113fee7a2fd08/tests/unit/Curves/SecCurveTest.php#L76-L103).

```php
$generator = EccFactory::getNistCurves()->generator256();
```

**Comment by mkrasselt1** [comment]
oh yeah that works, didnt know that!  that makes it solved!
